version: "3.6"
services:
  app-db:
    restart: always
    container_name: maria_db
    image: linuxserver/mariadb:alpine
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=budget
      - MYSQL_USER=budget-keeper
      - MYSQL_PASSWORD=123Budget#
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  app:
    build: .
    depends_on:
      - app-db