version: "3.6"
services:
  app:
    build: .
    restart: unless-stopped
    networks:
      - budget
    depends_on:
      - db
  db:
    restart: always
    container_name: db
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=budget
      - MYSQL_USER=budget-keeper
      - MYSQL_PASSWORD=123Budget#
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
    networks:
      - budget

networks:
  budget:
    name: budget
    driver: bridge
