version: "3"
services:
  app-db:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=budget
      - MYSQL_TCP_PORT=3307
      - MYSQL_USER=budget-keeper
      - MYSQL_PASSWORD=123Budget#
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  app:
    restart: always
    build: .
    depends_on:
      - app-db