version: "3.6"
services:
  app:
    build: '.'
    container_name: "app"
    restart: unless-stopped
    networks:
      - budget
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - budget

networks:
  budget:
    name: budget
    driver: bridge
