version: "3.6"
services:
  app-db:
    restart: unless-stopped
    container_name: maria_db
    image: linuxserver/mariadb:alpine
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=budget
      - MYSQL_USER=budget-keeper
      - MYSQL_PASSWORD=123Budget#
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - app-db
